#!/bin/sh

. /etc/rc.common

##
# Start up the PostgreSQL database server on Mac OS X / Darwin
#
#
# History
# -------
#
# 2010-09-22  Andy Satori <dru@druware.com>
#             altered to the new /Library/PostgreSQL/ path replacing the 
#             version specific PostgreSQL8 paths
#
# 2009-02-27  Andy Satori <dru@druware.com>
#             Altered to support reading DATA, LOG and AUTOSTART from a plist
#             to support the preference panel options
#
# 2009-01-06  Andy Satori <dru@druware.com>
#             Added a 'RELOAD' option to the Restart call to allow a forced
#             reload of the pg_hba.conf and postgresql.conf files
#
# 2008-11-06  Andy Satori <dru@druware.com>
#             Refactored DATA_PATH and LOG_FILE our to variables to make them
#             easier to maintain and adjust from the GUI Preference Pane and 
#             associated tools.
#
# 2007-04-02  Andy Satori <dru@druware.com>
#             Added manual-restart manual-start options for use with the 
#             startup manager and allow the user to use hostconfig properly.
#             (probably last change before moving to launchd for leopard)
#
# 2005-02-28  Andy Satori <dru@druwaer.com >
#             Modified to resolve issues with the Postgres user not having a
#             Shell defined (su -m)
#
# 2005-02-07  Andy Satori <dru@druware.com>
#             Updated for the new PostgreSQL8 package from Druware
#			  Software Designs
#
# 2004-03-09  Andy Satori <dru@druware.com>
#             Modified to use the /Library/PostgreSQL/Data path
#             and place logs in /Library/Logs/PostgreSQL.log for
#             use with the /Applications/Utilities/Console.app
#
# 2002-08-21  Marc Liyanage <liyanage@access.ch>
#             Changed startup to use pg_ctl
#
# 2002-08-19  Ed Silva <ed@septicus.com>
#             Modified startup script to conform
#             to new SystemStarter format for Mac OS X 10.2
#
# 2001-04-02  Marc Liyanage <liyanage@access.ch>
#             First version
#
# 2001-12-02  Johan Henselmans <johanhenselmans@mac.com>
#             Enhanced after carefully studying the Frontbase
#             startup sequence ;-)
#             Now provides a stop procedure for a graceful shutdown
#             and a hard kill if the clean shutdown doesn't work.
#
# 2001-12-02  Marc Liyanage <liyanage@access.ch>
#             Added localized startup messages in 7 languages
#             by adapting the resources of the Apple-supplied
#             "Sendmail" startup script.
#
#
# License
# -------
#
# The PostgreSQL BSD-style license applies to this file
#

DATA_PATH="/Library/PostgreSQL/data"
LOG_FILE="/Library/PostgreSQL/log/PostgreSQL.log"
AUTO_START="YES"
MANUAL="NO"
RELOAD="NO"

# if the preferences file exists, read it.
if test -f "/Library/Preferences/com.druware.postgresqlformac.plist"; then
	X=`defaults read /Library/Preferences/com.druware.postgresqlformac | grep dataPath`
	if [ "$X" != "" ]; then
		DATA_PATH=`defaults read /Library/Preferences/com.druware.postgresqlformac dataPath`
	fi
	
	X=`defaults read /Library/Preferences/com.druware.postgresqlformac | grep logPath`
	if [ "$X" != "" ]; then
		LOG_FILE=`defaults read /Library/Preferences/com.druware.postgresqlformac logPath`
	fi
	
	X=`defaults read /Library/Preferences/com.druware.postgresqlformac | grep startAtBoot`
	if [ "$X" != "" ]; then
		AUTO_START=`defaults read /Library/Preferences/com.druware.postgresqlformac startAtBoot`
	fi
	
	X=`defaults read /Library/Preferences/com.druware.postgresqlformac | grep manual`
	if [ "$X" != "" ]; then
		MANUAL=`defaults read /Library/Preferences/com.druware.postgresqlformac manual`
	fi

	X=`defaults read /Library/Preferences/com.druware.postgresqlformac | grep reload`
	if [ "$X" != "" ]; then
		RELOAD=`defaults read /Library/Preferences/com.druware.postgresqlformac reload`
	fi	
fi

# display the options in the log
ConsoleMessage "PostgreSQL Data Path: $DATA_PATH"
ConsoleMessage "PostgreSQL Log Path: $LOG_FILE"
ConsoleMessage "PostgreSQL Auto Starts: $AUTO_START"
ConsoleMessage "PostgreSQL Manual: $MANUAL"
ConsoleMessage "PostgreSQL Reload: $RELOAD"

overrideEnvironment='-NO-'
reloadOnRestart='-NO-'

if [ "$MANUAL" = "YES" ]; then
	overrideEnvironment='-YES-'
fi
if [ "$RELOAD" = "YES" ]; then
	reloadOnRestart='-YES-'
fi

# on the off chance this gets called the old way, read the options from the 
# command line
for f in "$@"
do
	if [ "$f" = "MANUAL" ]; then
		overrideEnvironment='-YES-'
	fi
	if [ "$f" = "RELOAD" ]; then
		reloadOnRestart='-YES-'
	fi
done

StartService ()
{
	shouldStartPostgres="-NO-"
	
	if [ "${POSTGRES:=-YES-}" = "-YES-" ]; then
		if [ "$AUTO_START" = "YES" ]; then
			shouldStartPostgres="-YES-"
		fi
	fi
	
	if [ "$overrideEnvironment" = "-YES-" ]; then
		shouldStartPostgres="-YES-"
	fi
		
	if [ "$shouldStartPostgres" = "-YES-" ]; then
	    ConsoleMessage "Starting PostgreSQL database server"
	    su -m postgres -c "/Library/PostgreSQL/bin/pg_ctl start -D $DATA_PATH -l $LOG_FILE -o -i"
	fi

}

StopService()
{
	ConsoleMessage "Stopping PostgreSQL database services"
	su -m postgres -c "/Library/PostgreSQL/bin/pg_ctl stop -D $DATA_PATH"
	
	sleep 1
	x=`ps auxwc | grep '^postgres' |grep 'postgres$' | awk -F" " '{print $2}'`
	if /bin/test "$x"
	then
		set $x
		kill -9 $x
	fi

}

RestartService ()
{
	if [ "$reloadOnRestart" = "-YES-" ]; then
		ConsoleMessage "Stopping PostgreSQL database services"
		su -m postgres -c "/Library/PostgreSQL/bin/pg_ctl reload -D $DATA_PATH"		
	else
		StopService
		sleep 1
		StartService
	fi
}

RunService "$1"

