#!/bin/sh

. /etc/rc.common

##
# Start up the PostgreSQL database server on Mac OS X / Darwin
#
#
# History
# -------
#
# 2007-04-02  Andy Satori <dru@druware.com>
#             Added manual-restart manual-start options for use with the 
#             startup manager and allow the user to use hostconfig properly.
#             (probably last change before moving to launchd for leopard)
#
# 2005-02-28  Andy Satori <dru@druwaer.com >
#             Modified to resolve issues with the Postgres user not having a
#             Shell defined (su -m)
#
# 2005-02-07  Andy Satori <dru@druware.com>
#             Updated for the new PostgreSQL8 package from Druware
#			  Software Designs
#
# 2004-03-09  Andy Satori <dru@druware.com>
#             Modified to use the /Library/PostgreSQL/Data path
#             and place logs in /Library/Logs/PostgreSQL.log for
#             use with the /Applications/Utilities/Console.app
#
# 2002-08-21  Marc Liyanage <liyanage@access.ch>
#             Changed startup to use pg_ctl
#
# 2002-08-19  Ed Silva <ed@septicus.com>
#             Modified startup script to conform
#             to new SystemStarter format for Mac OS X 10.2
#
# 2001-04-02  Marc Liyanage <liyanage@access.ch>
#             First version
#
# 2001-12-02  Johan Henselmans <johanhenselmans@mac.com>
#             Enhanced after carefully studying the Frontbase
#             startup sequence ;-)
#             Now provides a stop procedure for a graceful shutdown
#             and a hard kill if the clean shutdown doesn't work.
#
# 2001-12-02  Marc Liyanage <liyanage@access.ch>
#             Added localized startup messages in 7 languages
#             by adapting the resources of the Apple-supplied
#             "Sendmail" startup script.
#
#
# License
# -------
#
# The PostgreSQL BSD-style license applies to this file
#

# set the data path (this will be altered by the GUI configuration tools)
DATA_PATH="/Library/PostgreSQL8/data"
LOG_FILE="/Library/PostgreSQL8/log/PostgreSQL8.log"

StartService ()
{
	shouldStartPostgres="-NO-"
	
	if [ "${POSTGRES:=-YES-}" = "-YES-" ]; then
		shouldStartPostgres="-YES-"
	fi
	
	if [ "$overrideEnvironment" = "-YES-" ]; then
		shouldStartPostgres="-YES-"
	fi
		
	if [ "$shouldStartPostgres" = "-YES-" ]; then
	    ConsoleMessage "Starting PostgreSQL database server"
	    su -m postgres -c "/Library/PostgreSQL8/bin/pg_ctl start -D $DATA_PATH -l $LOG_FILE -o -i"
	fi

}

StopService()
{
	ConsoleMessage "Stopping PostgreSQL database services"
	su -m postgres -c "/Library/PostgreSQL8/bin/pg_ctl stop -D $DATA_PATH"
	
	sleep 1
	x=`ps auxwc | grep '^postgres' |grep 'postgres$' | awk -F" " '{print $2}'`
	if /bin/test "$x"
	then
		set $x
		kill -9 $x
	fi

}

RestartService ()
{
    StopService
    sleep 1
    StartService
}


overrideEnvironment='-NO-'
for f in "$@"
do
	if [ "$f" = "MANUAL" ]; then
		overrideEnvironment='-YES-'
	fi
done

RunService "$1"

