#!/bin/sh
echo ...running preflight

# first let's make sure the the postgres user does
# not currently exist

# Leopard/Tiger - this no longer works on Panther

echo Checking for Postgres group...
PG_GID=`/usr/bin/dscl . read /groups/postgres PrimaryGroupID | grep "PrimaryGroupID:.[0-9]" | sed 's/.*: //' | sed 's/ //'`
if test $PG_GID; then
	echo ...found Postgres with GID of $PG_GID
else
	echo ...Postgres group not found
		
	# loop through the '400's' until we find an available gid
	X=401
	until test $PG_GID; do
		TEST_GID=`/usr/bin/dscl . search /groups PrimaryGroupID $X | grep $X `
		
		if test $TEST_GID; then
			echo ...Group ID $X is not available
		else
			echo ...Group ID $X is available, 
			PG_GID=$X
		fi
		X=`expr $X + 1`
	done
	
	sudo /usr/bin/dscl . -create /groups/postgres PrimaryGroupID $PG_GID
	echo ...Group postgres created with GID $PG_GID
fi

echo Checking for Postgres user...
PG_UID_NOT_FOUND=0
PG_UID=`/usr/bin/dscl . -read /users/postgres | grep "^UniqueID:.[0-9]" | sed 's/.*: //' | sed 's/ //'`
if test $PG_UID; then
	echo ...found user postgres with UID of $PG_UID
else
	echo ...user postgres not found
	PG_UID_NOT_FOUND=1

	# loop through the '400's' until we find an available gid
	X=401
	until test $PG_UID; do
		TEST_UID=`/usr/bin/dscl . -search /users UniqueID $X | grep $X `
		
		if test $TEST_UID; then
			echo ...Unique ID $X is not available
		else
			echo ...Unique ID $X is available, 
			PG_UID=$X
		fi
		X=`expr $X + 1`
	done
	
	sudo /usr/bin/dscl . -create /users/postgres UniqueID $PG_UID
	sudo /usr/bin/dscl . -append /users/postgres PrimaryGroupID $PG_GID
	sudo /usr/bin/dscl . -append /users/postgres UserShell /bin/bash
	sudo /usr/bin/dscl . -append /users/postgres RealName "PostgreSQL Server"
#	sudo /usr/bin/dscl . -append /users/postgres NFSHomeDirectory /var/empty
	sudo /usr/bin/dscl . -append /users/postgres NFSHomeDirectory /Library/PostgreSQL8
	
	echo ...User postgres created with UID $PG_UID
fi

# in the case of an upgrade, we need to move aside the current version and 
# install the newest, but also to compare the version information.

if test -L /Library/PostgreSQL8/bin; then
	X=`ls -al /Library/PostgreSQL8/ | grep bin | grep versions`
	if ! test -z $X; then
		echo already using symlink structure, will call setVersion at the end.
	else
		echo /Library/PostgreSQL8/bin is a symlink but not to the versions
		echo folder.  Exiting because we cannot deal with this configuration.
		exit 1
	fi
else
	echo upgrading an existing install with old directory layout, moving to new.
	
	# get the current version
	CURRENT_VERSION=`/Library/PostgreSQL8/bin/psql --version | grep 'psql' | awk -F" " '{print $3}'`
	echo testing: $CURRENT_VERSION
	
	if ! test -d /Library/PostgreSQL8/versions/$CURRENT_VERSION; then
		mkdir -p /Library/PostgreSQL8/versions/$CURRENT_VERSION
	fi 
	
	mv /Library/PostgreSQL8/bin /Library/PostgreSQL8/versions/$CURRENT_VERSION/
	mv /Library/PostgreSQL8/lib /Library/PostgreSQL8/versions/$CURRENT_VERSION/
	mv /Library/PostgreSQL8/include /Library/PostgreSQL8/versions/$CURRENT_VERSION/
	mv /Library/PostgreSQL8/share /Library/PostgreSQL8/versions/$CURRENT_VERSION/	
	mv /Library/PostgreSQL8/data /Library/PostgreSQL8/versions/$CURRENT_VERSION/	
fi
	
echo completed preflight 



